const CONFIG={whatsapp:"",phone:"",version:"4.0"};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const toast=$("#toast");let toastTimer;function showToast(t){if(!toast)return;clearTimeout(toastTimer);toast.textContent=t;toast.classList.add("show");toastTimer=setTimeout(()=>toast.classList.remove("show"),3200)}
const menuBtn=$(".menu-btn"),mobileMenu=$(".mobile-menu");if(menuBtn&&mobileMenu){menuBtn.addEventListener("click",()=>{const open=mobileMenu.classList.toggle("open");document.body.classList.toggle("menu-open",open);menuBtn.setAttribute("aria-expanded",String(open))});$$('.mobile-menu a').forEach(a=>a.addEventListener('click',()=>{mobileMenu.classList.remove('open');document.body.classList.remove('menu-open');menuBtn.setAttribute('aria-expanded','false')}))}
const modal=$("#wa-modal"),modalText=$("#wa-message"),modalClose=$("#wa-close"),copyBtn=$("#wa-copy");let pending="";function closeModal(){modal?.classList.remove("open");document.body.classList.remove("menu-open")}
function openWhatsApp(message){pending=message;if(CONFIG.whatsapp){window.open(`https://wa.me/${CONFIG.whatsapp}?text=${encodeURIComponent(message)}`,"_blank","noopener");return}if(modalText)modalText.textContent=message;modal?.classList.add("open");document.body.classList.add("menu-open")}
$$('.js-wa').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();openWhatsApp(el.dataset.waMessage||'Ciao, vorrei ricevere un preventivo.')}));modalClose?.addEventListener('click',closeModal);modal?.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});copyBtn?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(pending);showToast('Messaggio copiato.')}catch{showToast('Seleziona e copia il testo manualmente.')}});
const form=$("#quote-form");if(form){const f={service:$("#service"),size:$("#size"),condition:$("#condition"),city:$("#city"),stains:$("#stains"),pets:$("#pets"),odor:$("#odor"),urgent:$("#urgent"),notes:$("#notes")},estimate=$("#estimate-price");const bases={divano:90,materasso:60,auto:120,b2b:160},factor={small:.85,medium:1,large:1.35,xl:1.7},condition={light:0,normal:15,heavy:45};function calc(){let low=bases[f.service.value]*factor[f.size.value]+condition[f.condition.value];if(f.stains.checked)low+=15;if(f.pets.checked)low+=25;if(f.odor.checked)low+=15;if(f.urgent.checked)low+=20;low=Math.round(low/5)*5;const high=Math.round(low*1.28/5)*5;estimate.textContent=`€${low}–${high}`;return{low,high}}Object.values(f).forEach(el=>el?.addEventListener('input',calc));const qs=new URLSearchParams(location.search),requested=qs.get('service'),requestedSize=qs.get('size'),requestedCondition=qs.get('condition');if(requested&&bases[requested])f.service.value=requested;if(requestedSize&&factor[requestedSize])f.size.value=requestedSize;if(requestedCondition&&Object.prototype.hasOwnProperty.call(condition,requestedCondition))f.condition.value=requestedCondition;['stains','pets','odor','urgent'].forEach(key=>{if(qs.get(key)==='1'&&f[key])f[key].checked=true});calc();form.addEventListener('submit',e=>{e.preventDefault();const{low,high}=calc(),labels={divano:'divano / poltrona',materasso:'materasso',auto:'interni auto',b2b:'servizio per azienda / struttura'},extras=[];if(f.stains.checked)extras.push('macchie evidenti');if(f.pets.checked)extras.push('peli di animali');if(f.odor.checked)extras.push('odori persistenti');if(f.urgent.checked)extras.push('richiesta urgente');const msg=[`Ciao, vorrei un preventivo per ${labels[f.service.value]}.`,`Dimensione: ${f.size.options[f.size.selectedIndex].text}.`,`Condizione: ${f.condition.options[f.condition.selectedIndex].text}.`,extras.length?`Extra: ${extras.join(', ')}.`:'',f.city.value?`Zona: ${f.city.value.trim()}.`:'',f.notes.value?`Note: ${f.notes.value.trim()}.`:'',`Stima del sito: €${low}–${high}.`,'Posso inviare le foto per confermare il prezzo?'].filter(Boolean).join('\n');openWhatsApp(msg)})}
const year=$("#year");if(year)year.textContent=new Date().getFullYear();const cookie=$("#cookie"),cookieOk=$("#cookie-ok");if(cookie&&cookieOk){let accepted=false;try{accepted=localStorage.getItem('memento-cookie-ok')==='1'}catch{}if(!accepted)cookie.classList.add('show');cookieOk.addEventListener('click',()=>{try{localStorage.setItem('memento-cookie-ok','1')}catch{}cookie.classList.remove('show')})}
